version: '3'

services:
  battleship:
    container_name: battleship
    image: reverseproxy
    build:
      context: .
      dockerfile: Dockerfile.reverseproxy
    ports:
      - 9999:9999
    restart: unless-stopped
